name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # --------------------------------------------------
  # 1. Wakatime Metrics
  # --------------------------------------------------
  wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Wakatime metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: udaysh134

          # Template & base
          template: classic
          base: ""

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_limit: 5
          plugin_wakatime_days: 365
          plugin_wakatime_languages_other: yes
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          # plugin_wakatime_url: https://wakatime.com
          # plugin_wakatime_user: current

          # Output
          filename: assets/wakatime_metrics.svg
