name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------
      # 1. Profile Metrics
      # --------------------------------------------------
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: udaysh134

          template: repository
          base: activity

          filename: assets/metrics/profile_metrics.svg

      # --------------------------------------------------
      # 2. Language Metrics
      # --------------------------------------------------
      - name: Generate language metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: udaysh134

          base: ""
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_languages_colors: github

          filename: assets/metrics/language_metrics.svg

      # --------------------------------------------------
      # 3. Mildly Interesting Facts
      # --------------------------------------------------
      - name: Generate habits metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: udaysh134

          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          filename: assets/metrics/facts_metrics.svg